### ISSUE TITLE
SoundDesign Todo List

### ISSUE THREAD

**Issue by Rovel** [Daza7/UE4GameDev#1]
# Sounds Required

- [x] Start menu bg music
- [ ] Main game bg music
- [x] Hover mouse sound
- [x] Button click
- [ ] Switch activation
- [ ] Switch fail
- [ ] Bot activate
- [ ] Bot dies
- [ ] No more bots
- [ ] Puzzle complete
